import { ImageResponse } from "@vercel/og";
import { NextRequest } from "next/server";

export const runtime = "edge";

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);

    const bg = searchParams.get("bg") || "bg-zinc-900";
    const text = searchParams.get("text") || "（※LGTM）";

    let bgColor = "#18181b";
    if (bg.includes("purple-500")) bgColor = "#a855f7";
    else if (bg.includes("cyan-500")) bgColor = "#06b6d4";
    else if (bg.includes("gray-900")) bgColor = "#111827";
    else if (bg.includes("green-400")) bgColor = "#4ade80";
    else if (bg.includes("orange-400")) bgColor = "#fb923c";
    else if (bg.includes("emerald-500")) bgColor = "#10b981";
    else if (bg.includes("indigo-500")) bgColor = "#6366f1";
    else if (bg.includes("rose-500")) bgColor = "#f43f5e";
    else if (bg.includes("amber-500")) bgColor = "#f59e0b";
    else if (bg.includes("slate-800")) bgColor = "#1e293b";

    return new ImageResponse(
      (
        <div
          style={{
            height: "100%",
            width: "100%",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: bgColor,
            position: "relative",
            overflow: "hidden",
            fontFamily: "sans-serif",
          }}
        >
          <div
            style={{
              position: "absolute",
              top: "-50%",
              left: "-10%",
              width: "120%",
              height: "120%",
              background: "radial-gradient(circle, rgba(255,255,255,0.1) 0%, rgba(0,0,0,0.5) 100%)",
              zIndex: 0,
            }}
          />

          <div
            style={{
              display: "flex",
              fontSize: 180, // Reduced from 240
              fontWeight: 900,
              color: "white",
              letterSpacing: "-0.05em",
              lineHeight: 1,
              zIndex: 1,
              textShadow: "0px 10px 30px rgba(0,0,0,0.4)",
              marginBottom: 10, // Slightly reduced margin
            }}
          >
            LGTM
          </div>

          <div
            style={{
              display: "flex",
              fontSize: 48,
              fontWeight: 700,
              color: "#fcd34d",
              zIndex: 1,
              textShadow: "0px 4px 12px rgba(0,0,0,0.5)",
              padding: "0 40px",
              textAlign: "center",
              wordWrap: "break-word",
            }}
          >
            {text}
          </div>

          <div
            style={{
              position: "absolute",
              bottom: 30,
              right: 40,
              display: "flex",
              fontSize: 20,
              fontWeight: 600,
              color: "rgba(255,255,255,0.5)",
              zIndex: 1,
              letterSpacing: "0.05em",
            }}
          >
            Generated by @YourXAccount
          </div>
        </div>
      ),
      {
        width: 1200,
        height: 630,
      }
    );
  } catch (e: any) {
    console.error(e);
    return new Response(`Failed to generate the image`, {
      status: 500,
    });
  }
}